//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileOrbis.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileOrbis.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification (default null).
        /// </summary>
        public static string FileOrbisFileUpload_Classification_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Classification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string FileOrbisFileUpload_Classification_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Classification_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileOrbisFileUpload_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Path.
        /// </summary>
        public static string FileOrbisFileUpload_DirectoryPath_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_DirectoryPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryPath.
        /// </summary>
        public static string FileOrbisFileUpload_DirectoryPath_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_DirectoryPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOrbisFileUpload.
        /// </summary>
        public static string FileOrbisFileUpload_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DType (default 0).
        /// </summary>
        public static string FileOrbisFileUpload_DType_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_DType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DType.
        /// </summary>
        public static string FileOrbisFileUpload_DType_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_DType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Full Path.
        /// </summary>
        public static string FileOrbisFileUpload_FileFullPath_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_FileFullPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileFullPath.
        /// </summary>
        public static string FileOrbisFileUpload_FileFullPath_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_FileFullPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Id.
        /// </summary>
        public static string FileOrbisFileUpload_FolderId_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_FolderId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderId.
        /// </summary>
        public static string FileOrbisFileUpload_FolderId_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_FolderId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        public static string FileOrbisFileUpload_ItemId_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_ItemId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemId.
        /// </summary>
        public static string FileOrbisFileUpload_ItemId_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_ItemId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string FileOrbisFileUpload_ItemName_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_ItemName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemName.
        /// </summary>
        public static string FileOrbisFileUpload_ItemName_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_ItemName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Relative Path.
        /// </summary>
        public static string FileOrbisFileUpload_ItemRelativePath_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_ItemRelativePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemRelativePath.
        /// </summary>
        public static string FileOrbisFileUpload_ItemRelativePath_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_ItemRelativePath_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string FileOrbisFileUpload_Success_Description
        {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Success_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string FileOrbisFileUpload_Success_DisplayName
        {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Success_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite (default true).
        /// </summary>
        public static string FileOrbisFileUpload_Overwrite_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string FileOrbisFileUpload_Overwrite_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Overwrite_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Body.
        /// </summary>
        public static string FileOrbisFileUpload_RequestBody_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_RequestBody_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestBody.
        /// </summary>
        public static string FileOrbisFileUpload_RequestBody_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_RequestBody_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Response.
        /// </summary>
        public static string FileOrbisFileUpload_Response_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string FileOrbisFileUpload_Response_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Token.
        /// </summary>
        public static string FileOrbisFileUpload_Token_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string FileOrbisFileUpload_Token_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Token_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL + &quot;/api/v2/filesystem/upload&quot;.
        /// </summary>
        public static string FileOrbisFileUpload_Url_Description {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Url_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string FileOrbisFileUpload_Url_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisFileUpload_Url_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Body.
        /// </summary>
        public static string FileOrbisLink_Body_Description {
            get {
                return ResourceManager.GetString("FileOrbisLink_Body_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string FileOrbisLink_Body_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLink_Body_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileOrbisLink_Description {
            get {
                return ResourceManager.GetString("FileOrbisLink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOrbisLink.
        /// </summary>
        public static string FileOrbisLink_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLink_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string FileOrbisLink_Link_Description {
            get {
                return ResourceManager.GetString("FileOrbisLink_Link_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string FileOrbisLink_Link_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLink_Link_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Response.
        /// </summary>
        public static string FileOrbisLink_Response_Description {
            get {
                return ResourceManager.GetString("FileOrbisLink_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string FileOrbisLink_Response_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLink_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Token.
        /// </summary>
        public static string FileOrbisLink_Token_Description {
            get {
                return ResourceManager.GetString("FileOrbisLink_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string FileOrbisLink_Token_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLink_Token_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL + &quot;/api/v2/link/create&quot;.
        /// </summary>
        public static string FileOrbisLink_Url_Description {
            get {
                return ResourceManager.GetString("FileOrbisLink_Url_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string FileOrbisLink_Url_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLink_Url_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileOrbisLogin_ClientId_Description {
            get {
                return ResourceManager.GetString("FileOrbisLogin_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId.
        /// </summary>
        public static string FileOrbisLogin_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLogin_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileOrbisLogin_Description {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOrbisLogin.
        /// </summary>
        public static string FileOrbisLogin_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLogin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileOrbisLogin_Password_Description {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string FileOrbisLogin_Password_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileOrbisLogin_Token_Description {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string FileOrbisLogin_Token_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Token_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileOrbisLogin_Url_Description {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Url_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string FileOrbisLogin_Url_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Url_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileOrbisLogin_Username_Description {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Username_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string FileOrbisLogin_Username_DisplayName {
            get {
                return ResourceManager.GetString("FileOrbisLogin_Username_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
